default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: test_rails_kaungkaung_development
  username: kaungkaung
  password: kaung@c2l
  host: localhost

test:
  <<: *default
  database: test_rails_kaungkaung_test
  username: kaungkaung
  password: kaung@c2l
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
